[tool.poetry]
name = "galah"
version = "1.0.0"
description = "Get counts and information on species"
authors = ["Amanda Buyan"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
