[tool.poetry]
name = "galah"
version = "0.1.0" # for testing
description = "Get counts and information on species"
authors = ["Amanda Buyan"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
shutils = "^0.1.0"
bytesbufio = "^1.0.3"
glob2 = "^0.7"
configparser = "^5.3.0"
requests = "^2.28.2"
urllib3 = "^1.26.14"
time-python = "^0.0.16"
zip-files = "^0.4.1"
pandas = "^1.5.3"
numpy = "^1.24.1"
unittest2 = "^1.1.0"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
